using './bff-web-app.module.bicep'

param app_outputs_clientid = '{{ .Env.APP_CLIENTID }}'
param app_outputs_identifieruri = '{{ .Env.APP_IDENTIFIERURI }}'
param app_outputs_keyvaultsecret = '{{ .Env.APP_KEYVAULTSECRET }}'
param app_outputs_keyvaulturl = '{{ .Env.APP_KEYVAULTURL }}'
param app_outputs_uamiid = '{{ .Env.APP_UAMIID }}'
param bff_web_app_containerimage = '{{ .Image }}'
param bff_web_app_containerport = '{{ targetPortOrDefault 8080 }}'
param outputs_azure_container_apps_environment_default_domain = '{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}'
param outputs_azure_container_apps_environment_id = '{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}'
param outputs_azure_container_registry_endpoint = '{{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}'
param outputs_azure_container_registry_managed_identity_id = '{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}'
param outputs_managed_identity_client_id = '{{ .Env.MANAGED_IDENTITY_CLIENT_ID }}'
param tenantid_value = '{{ parameter "TenantId" }}'
